---
# vars file for docker

backup:
  backup_path: /mnt/backup/docker
  backup_filename: docker-backup.sh
  restore_filename: docker-restore.sh
  control_filename: docker-backup-control.sh
  systemd_name: docker-data-backup
  systemd_time: "03:30:00"

# Set version for each docker compose file
docker:
  cops: version-4.5.4
  fritzbox_exporter: 50ebd8ff4588208b46fe7caed312903e18f96d3b
  homeassistant: stable
  mealie: v3.28.0
  cadvisor: v0.55.1
  node_exporter: v1.12.1
  grafana: 13.2.3
  prometheus: v3.15.0
  traefik: v3.7.13
  wud: 9.2.1
  socket_proxy: v0.5.0
  gethomepage: v2.4.0
  jellyfin: 12.1

fritzbox_exporter:
  user: monitor
  gateway: http://192.168.10.1:49000

gethomepage:
  config_files:
    - template: gethomepage-settings.j2
      dest: "{{ dockerall.data_path }}gethomepage-data/settings.yaml"
    - template: gethomepage-docker.j2
      dest: "{{ dockerall.data_path }}gethomepage-data/docker.yaml"
    - template: gethomepage-services.j2
      dest: "{{ dockerall.data_path }}gethomepage-data/services.yaml"
    - template: gethomepage-widgets.j2
      dest: "{{ dockerall.data_path }}gethomepage-data/widgets.yaml"