---
# vars file for docker

backup:
  backup_path: /mnt/backup/docker
  backup_filename: docker-backup.sh
  restore_filename: docker-restore.sh
  control_filename: docker-backup-control.sh
  systemd_name: docker-data-backup
  systemd_time: "03:30:00"

# Set version for each docker compose file
docker:
  cops: version-4.5.4
  fritzbox_exporter: 50ebd8ff4588208b46fe7caed312903e18f96d3b
  homeassistant: stable
  mealie: v3.28.0
  cadvisor: v0.55.1
  node_exporter: v1.12.1
  grafana: 13.2.3
  prometheus: v3.15.0
  traefik: v3.7.14
  wud: 9.3.0
  socket_proxy: v0.5.0
  gethomepage: v2.4.0
  jellyfin: 12.2
  valkey: 9-alpine
  paperless_ngx: 3.3.0

cops:
  template_check:
    - { src: cops.j2, dest: "{{ dockerall.compose_files_path }}cops/docker-compose.yaml" }
    - { src: cops_local_php.j2, dest: "{{ dockerall.compose_files_path }}cops/local.php" }

fritzbox_exporter:
  user: monitor
  gateway: http://192.168.10.1:49000
  template_check:
    - { src: fritzbox_exporter.j2, dest: "{{ dockerall.compose_files_path }}fritzbox_exporter/docker-compose.yaml" }

gethomepage:
  template_check:
    - { src: gethomepage.j2, dest: "{{ dockerall.compose_files_path }}gethomepage/docker-compose.yaml" }
    - { src: gethomepage-settings.j2, dest: "{{ dockerall.data_path }}gethomepage-data/settings.yaml" }
    - { src: gethomepage-docker.j2, dest: "{{ dockerall.data_path }}gethomepage-data/docker.yaml" }
    - { src: gethomepage-services.j2, dest: "{{ dockerall.data_path }}gethomepage-data/services.yaml" }
    - { src: gethomepage-widgets.j2, dest: "{{ dockerall.data_path }}gethomepage-data/widgets.yaml" }
    - { src: gethomepage-bookmarks.j2, dest: "{{ dockerall.data_path }}gethomepage-data/bookmarks.yaml" }

homeassistant:
  template_check:
    - { src: homeassistant.j2, dest: "{{ dockerall.compose_files_path }}homeassistant/docker-compose.yaml" }

jellyfin:
  template_check:
    - { src: jellyfin.j2, dest: "{{ dockerall.compose_files_path }}jellyfin/docker-compose.yaml" }

mealie:
  template_check:
    - { src: mealie.j2, dest: "{{ dockerall.compose_files_path }}mealie/docker-compose.yaml" }

monitor_clients:
  template_check:
    - { src: monitor_clients.j2, dest: "{{ dockerall.compose_files_path }}monitor_clients/docker-compose.yaml" }

monitor:
  template_check:
    - { src: monitor.j2, dest: "{{ dockerall.compose_files_path }}monitor/docker-compose.yaml" }
    - { src: prometheus.j2, dest: "{{ dockerall.data_path }}monitor/prometheus.yml" }

traefik:
  template_check:
    - { src: traefik.j2, dest: "{{ dockerall.compose_files_path }}traefik/docker-compose.yaml" }

wud:
  template_check:
    - { src: wud.j2, dest: "{{ dockerall.compose_files_path }}wud/docker-compose.yaml" }

paperless_ngx:
  template_check:
    - { src: paperless-ngx.j2, dest: "{{ dockerall.compose_files_path }}paperless-ngx/docker-compose.yaml" }
  mediafolder: /mnt/Aktenschrank/Ablage
  consumefolder: /mnt/Aktenschrank/Eingang
  exportfolder: /mnt/Aktenschrank/Ausgang
