# Group vars file for all docker machines

main:
  hostname: jarvis.fritz.box

dockerall:
  id: 1002
  group: 100
  path: /srv/docker/
  compose_files_path: /srv/docker/docker/
  data_path: /srv/docker/data/
  internal_network: traefik_internal
  external_network: traefik_external