---
# task for nfs mount
  - name: install nfs tools
    apt:
      name: nfs-common
      state: present
      force_apt_get: yes
      update_cache: yes
# Create mount directory for calibre
  - name: Ensure calibre directory exists
    file:
      dest: "/mnt/calibre"
      state: directory
# Mount calibre directory from Synology
  - name: Mount share from nfs server
#    become: yes
    ansible.posix.mount:
      src: "{{ nfs_server }}:/volume1/calibre"
      path: /mnt/calibre
      state: mounted
      fstype: nfs
# Create mount directory for backup
  - name: Ensure backup directory exists
    file:
      dest: "/mnt/backup"
      owner: docker
      group: docker
      state: directory
# Mount backup directory from Synology
  - name: Mount share from nfs server
#    become: yes
    ansible.posix.mount:
      src: "{{ nfs_server }}:/volume1/backup"
      path: /mnt/backup
      state: mounted
      fstype: nfs