---
  - name: copy ssh config file for git
    copy:
      src: config
      dest: /home/ansible/.ssh/config
      owner: ansible
      group: ansible
      mode: '0600'
  - name: copy gitconfig file
    copy:
      src: .gitconfig
      dest: /home/ansible/.gitconfig
      owner: ansible
      group: ansible
      mode: '0644'