---
# Install docker prerequisites and rsync for backup
- name: Install docker prerequisites and update message of the day packages
  apt:
    pkg:
      - ca-certificates
      - curl
      - rsync
    state: latest
    update_cache: true

# Add Docker repository
- name: Add Docker repository
  block:
    - name: Add Docker key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

# Install docker
- name: Install docker
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest
    update_cache: true

# Add docker user as default deploy user
- name: Add docker user
  user:
    name: docker
    comment: docker
    shell: /bin/bash
    group: users
    groups: docker
    append: yes
    state: present
- name: Add public key for docker
  authorized_key:
    user: docker
    state: present
    key: "{{ lookup('file', 'mario_sha2.pub') }}"
- name: Ensure docker directory exists
  file:
    dest: "/srv/docker"
    mode: 0775
    owner: "docker"
    group: "docker"
    state: directory
