[ansible]
raspberrypi ansible_host=192.168.10.99 ansible_python_interpreter=/usr/bin/python3 os=raspberrypios

[docker]
jarvis	ansible_host=192.168.10.51 ansible_python_interpreter=/usr/bin/python3

[playgrounds]
playground ansible_host=192.168.10.50 ansible_python_interpreter=/usr/bin/python3