# Create docker networks
- name: Create docker external network
  docker_network:
    name: "{{ dockerall.external_network }}"
    state: present
    driver: bridge

- name: Create docker internal network
  docker_network:
    name: "{{ dockerall.internal_network }}"
    state: present
    driver: bridge