---
# task to setup fritzbox-exporter
- name: Check, if docker-compose file exists
  stat:
    path: "{{ main.docker_compose_files_path }}fritzbox_exporter/docker-compose.yaml"
  register: docker_compose

- name: Create fritzbox_exporter directory
  file:
    path: "{{ main.docker_compose_files_path }}fritzbox_exporter"
    state: directory
    owner: docker
    group: docker
  when: not docker_compose.stat.exists

- name: Stop fritzbox_exporter container
  command: docker compose down
  args:
    chdir: "{{ main.docker_compose_files_path }}fritzbox_exporter"
  when: docker_compose.stat.exists

- name: Copy fritzbox_exporter compose file
  template:
    src: fritzbox_exporter.j2
    dest: "{{ main.docker_compose_files_path }}fritzbox_exporter/docker-compose.yaml"
    owner: docker
    group: docker
    mode: '0644'

- name: Start fritzbox_exporter container
  command: docker compose up -d
  args:
    chdir: "{{ main.docker_compose_files_path }}fritzbox_exporter"
