---
# tasks file for setup
- name: Install scripts and systemd for backup
  include_tasks: backup.yml

- name: Install traefik
  include_tasks: traefik.yml

- name: Install fritzbox exporter
  include_tasks: fritzbox_exporter.yml

- name: Install monitor clients
  include_tasks: monitor_clients.yml

- name: Install monitor toolset
  include_tasks: monitor.yml

- name: Install mealie
  include_tasks: mealie.yml

- name: Install cops
  include_tasks: cops.yml

- name: Install wud
  include_tasks: wud.yml