---
# task to setup paperless-ngx
- name: Check, if docker-compose file exists
  stat:
    path: "{{ dockerall.compose_files_path }}paperless-ngx/docker-compose.yaml"
  register: docker_compose

- name: Check, if one of the files will be changed
  template:
    src: "{{ item.src}}"
    dest: "{{ item.dest }}"
  check_mode: true
  loop: "{{ paperless_ngx.template_check }}"
  register: template_check_result

- name: Create paperless-ngx directory
  file:
    path: "{{ dockerall.compose_files_path }}paperless-ngx"
    state: directory
    owner: docker
    group: docker
  when: not docker_compose.stat.exists

- name: Check, if paperless-ngx data folder exists
  stat:
    path: "{{ dockerall.data_path }}paperless-ngx-data"
  register: paperless_data

- name: Create paperless-ngx data for redis directory
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ nas.userid }}"
    group: "{{ nas.groupid }}"
  loop:
    - "{{ dockerall.data_path }}paperless-ngx-data"
    - "{{ paperless_ngx.mediafolder }}"
    - "{{ paperless_ngx.consumefolder }}"
    - "{{ paperless_ngx.exportfolder }}"
  when: not paperless_data.stat.exists

- name: Change docker configuration for paperless-ngx and restart container if needed
  block:
  - name: Stop paperless-ngx container
    command: docker compose down
    args:
      chdir: "{{ dockerall.compose_files_path }}paperless-ngx"
    when: docker_compose.stat.exists

  - name: Copy paperless-ngx compose file
    template:
      src: "{{ item.src}}"
      dest: "{{ item.dest }}"
      owner: docker
      group: docker
      mode: '0644'
    loop: "{{ paperless_ngx.template_check }}"

  - name: Start paperless-ngx container
    command: docker compose up -d
    args:
      chdir: "{{ dockerall.compose_files_path }}paperless-ngx"

  when: template_check_result.results | selectattr('changed') | list | length > 0
