---
  - name: find files to copy
    find: 
      paths: "{{ role_path }}/files/scripts"
      recurse: true
      patterns: "*.sh"
    delegate_to: localhost
    register: files_to_copy

  - name: copy scripts
    copy: 
      src: "{{ item.path }}" 
      dest: "{{ main['docker-path'] }}{{ item.path | basename }}"
      owner: docker
      group: docker
      mode: 0775
    loop: "{{ files_to_copy.files }}"
